### ISSUE TITLE
space-before-function-paren rule not applied to formatted code

### ISSUE THREAD

**Issue by Ectropy** [prettier/prettier-atom#282]
I'm not sure if this is a problem with atom-prettier, prettier, or prettier-eslint. I do know that when I used atom-prettier's Ctrl-Shift-F formatting keystroke on a improperly formatted file, it fixed all of the eslint errors (based on the rules of [JavaScript Standard Style](https://github.com/standard/standard)) _except for_ the [space-before-function-paren](https://eslint.org/docs/rules/space-before-function-paren) eslint rule. That didn't seem like intended behavior to me.

See images below the break for an example:
<details>
Before prettier-atom
<img width="856" alt="before" src="https://user-images.githubusercontent.com/13873924/30726767-c6c38142-9f1a-11e7-9ca5-a94871f091a4.PNG">
After prettier-atom
<img width="854" alt="after" src="https://user-images.githubusercontent.com/13873924/30726773-d2a45e96-9f1a-11e7-89ee-8d7fd2793f72.PNG">
</details>

If you believe this issue is actually a problem with prettier or prettier-eslint, close it & let me know. I can post the issue there instead.

**Comment by robwise** [comment]
@Ectropy Yeah this is a prettier thing, it's the way it formats. If you'd like to change that, you can turn on prettier-atom's `ESLint Integration` option and it should run eslint's autofix after formatting with prettier, which should fix the problem.

**Comment by Ectropy** [comment]
Ok for some reason even with `ESLint Integration` on it still didn't seem to fix that style error. In any case, it's not a problem with this plugin, so I'll close.

**Comment by zaferkadi** [comment]
Has this been fixed yet? I'm having the same problem.

**Comment by robwise** [comment]
@zaferkadi this is not a prettier-atom issue
